### ISSUE TITLE
Cross-account region specification

### ISSUE THREAD

**Issue by pedroo21** [awslabs/aws-refarch-cross-account-pipeline#11]
Hello,

I've been looking into the repo and AWS tutorials on this cross-account matter. However, I wasn't able to find any reference to region specification when deploying cross-account. 

The deployment environment of the account is seen as a single unit, when there could possibly be multiple regions where to deploy in.

Is there an example on how we change the cross-account deployment region rather than the pipeline's default?

I've tried setting up a new region in the deployment stage, as well as another ArtifactBucket for the corresponding region.

```
    ArtifactStores:
        - Region: "eu-west-1"
          ArtifactStore:
            Type: S3
            Location: !Sub ${BucketName}-eu-west-1
            EncryptionKey:
              Id: !GetAtt KMSKey.Arn
              Type: KMS
        - Region: "ap-southeast-2"
          ArtifactStore:
            Type: S3
            Location: !Sub ${BucketName}-ap-southeast-2
```

But the end result is either: 
- Failed replicating 'Deployment Artifact': Invalid Arn (if I specify the  KMS key in the new bucket)
- Access Denied on S3 when the KMS key is only specified on the main artifact store, even with Role permissions and bucket policies extended to the new bucket.

Thanks.
